services:
  db:
    image: postgres:15-alpine
    container_name: webprog_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mozi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webprog_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:adminpassword@db:5432/mozi_db
      JWT_SECRET: super_secret_key_for_jwt_development
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/drizzle:/app/drizzle
      - ./backend/drizzle.config.ts:/app/drizzle.config.ts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webprog_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts

volumes:
  postgres_data:
